### ISSUE TITLE
After login user.name is undfined

### ISSUE THREAD

**Issue by maher1719** [trujic1000/mern-auth-bolierplate#2]
First of all **thank you so much for this repo** you literally saved me after days of long searching for a working project!!.
You should change mongo URI it is your personal URI.
After login user is undefined but after refreshing it works just fine, I found it in after login directly user is in object user.
It is like this user.user.name to work directly after login.

**Comment by trujic1000** [comment]
No problem man, if you need any help navigating around the project let me know. Thanks for pointing out some issues, I fixed em.

**Comment by maher1719** [comment]
Hello, can you tell me please how can I use private routes?  I used useEffect but it work at first when a person is authenticated and click to different private route it makes him back(with isAuth is false) to /login then comeback to /dashboard with isAuth is true,

**Comment by trujic1000** [comment]
Hey sorry for replying late, you should be able to use private routes as it is. When the app loads it checks for token in local storage and it checks if token expired. If it did expire, it redirect user back to login page, if not it sends him to the dashboard. From there you are authenticated and private routes should be working just fine. If you're having troubles send me link to your github repo and I can take a look.
